[tool.black]
line-length = 150
target-version = ["py37"]

[tool.isort]
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
line_length = 150
multi_line_output = 3
use_parentheses = true
